urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
import app.views

admin.autodiscover()

urlpatterns = [
    url(r'^$', app.views.index, { 'template' : 'thialfi/index.html' }, name = "views_index"),
    url(r'^messages/$', app.views.messages, { 'template' : 'thialfi/messages.html' }, name = "views_messages"),
    url(r'^detail/(?P<message_id>\d+)/$', app.views.detail, { 'template' : 'thialfi/detail.html' }, name = "views_detail"),
    url(r'^group/(?P<group_id>\d+)/$', app.views.group, { 'template' : 'thialfi/group.html' }, name = "views_group"),
    url(r'^tw/(?P<phonecall_id>\w+)/$', app.views.twilio, { 'template' : 'thialfi/twilio.xml' }, name = "views_twilio"),
    url(r'^report.csv$', app.views.report_csv, { 'template' : 'thialfi/report.csv' }),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    ## Serve static files only in debug mode
    import django.views.static
    urlpatterns.append(
        url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.PROJECT_ROOT + '/doc_root/static'}),
    )

app/models.py
from django.conf import settings
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.core.validators import RegexValidator
from django.contrib import admin
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone

from thialfi.logger import *
from thialfi.voice import twiliogw
import datetime
from sms import smsgw
from .random_primary import RandomPrimaryIdModel

__all__ = []

### Contact model

__all__.append("Contact")
class Contact(models.Model):
    name = models.CharField(max_length=200)
    sms_number = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "%s (%s)" % (self.name, self.sms_number)

admin.site.register(Contact)

### Group model

__all__.append("Group")
class Group(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank = True)
    contacts = models.ManyToManyField(Contact)
    contact_primary = models.ForeignKey(Contact, related_name = "contact_primary", help_text = "On-call contact", on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return str(self.name)

    def set_contact_primary(self, contact):
        assert(contact in self.contacts.all())
        old_contact = self.contact_primary
        self.contact_primary = contact
        self.save()
        return old_contact

class GroupAdmin(admin.ModelAdmin):
    list_display = ('name', 'contact_primary')

admin.site.register(Group, GroupAdmin)

### Recipient model

__all__.append("Recipient")
class Recipient(models.Model):
    address = models.CharField(max_length=500, help_text = 'Use only lowercase letters, digits and hyphens', validators = [ RegexValidator(r'^[a-z][a-z0-9\._-]+$', 'Use only lowercase letters, digits and hyphens') ])
    description = models.TextField(blank = True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    require_ack_min = models.IntegerField(default = 0, help_text = "Require ACK within X minutes or trigger Escalation. 0 means ACK not required.")
    escalation_group = models.ForeignKey(Group, related_name = "escalation_group", null = True, blank = True, help_text = "Non-ACKed messages will be escalated to this group's primary contact. If not set call the main Group again.", on_delete=models.CASCADE)
    dt_last_called = models.DateTimeField(null = True)

    class Meta:
        ordering = ['address']

    def __str__(self):
        return str(self.address)

    def domain(self):
        return settings.RCPT_DOMAIN

    def update_last_called(self):
        self.dt_last_called = timezone.now()
        self.save()

    def can_call(self):
        if not self.dt_last_called:
            return True
        return (timezone.now() - self.dt_last_called).total_seconds() > settings.CALL_GRACE_MIN * 60

class RecipientAdmin(admin.ModelAdmin):
    list_display = ('address', 'group', 'escalation_group')

admin.site.register(Recipient, RecipientAdmin)

### Message model

__all__.append("Message")
class Message(models.Model):
    header = models.TextField()
    body = models.TextField()
    # The "body" converted to sms format
    sms_body = models.TextField()
    # Some useful headers extracted
    hdr_subject = models.CharField(max_length=500)
    hdr_sender = models.CharField(max_length=500)
    hdr_recipient = models.CharField(max_length=500)
    hdr_message_id = models.CharField(max_length=500)
    # Resolved recipient
    recipient = models.ForeignKey(Recipient, on_delete=models.CASCADE)
    # Timestamp
    dt_received = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.sms_body

    def acknowledge(self, ack_by = "<unknown>"):
        info("{%d} ACK by %s" % (self.id, ack_by))
        self.add_status('acked', note = ack_by)

    def despatch(self):
        if self.get_status('delivered') or self.get_status('expired') or self.get_status('ignored'):
            return
        recent_timestamp = timezone.now() - datetime.timedelta(minutes = settings.RECENT_MINUTES)
        recent_messages = MessageStatus.objects.filter(
                status = 'received',
                message__recipient = self.recipient,
                message__dt_received__gt = recent_timestamp)
        if recent_messages.count() > settings.RECENT_MESSAGES:
            message = '%d messages received in the last %d minutes' % (recent_messages.count(), settings.RECENT_MINUTES)
            info("Ignoring message for %s: %s" % (self.recipient, message))
            self.add_status('ignored', note = message)
            return
        if self.delivery_set.all():
            ## Delivery in progress
            ## - update delivery status
            ## - if too old escalate or expire message
            self.update_status()
        else:
            ## No delivery attempted yet
            ## - despatch now
            delivery = Delivery(message = self, contact = self.recipient.group.contact_primary)
            status = smsgw.despatch(self, delivery.contact)
            if status.despatched:
                delivery.sms_id = status.mid
                delivery.status = status.status
                delivery.dt_despatched = status.timestamp
                delivery.save()

    def update_status(self):
        for delivery in self.delivery_set.all():
            delivery.update_status()

    def newest_status(self):
        ms_set = self.messagestatus_set.order_by("-pk")
        if ms_set:
            return ms_set[0]

    def add_status(self, status, note = ""):
        dt_status = timezone.now()
        MessageStatus(message = self, status = status, dt_status = dt_status, note = note).save()

    def get_status(self, status):
        ms_set = self.messagestatus_set.filter(status = status).order_by("-pk")
        if ms_set:
            return ms_set[0]
        return None

    def get_timestamp(self, status):
        ms = self.get_status(status)
        if ms:
            return ms.dt_status
        return None

    def older_than(self, timestamp, minutes):
        return bool(timestamp) and timestamp + datetime.timedelta(minutes = minutes) < timezone.now()

    def is_overdue(self):
        return self.process_escalation(dry_run = True)

    def sync_acks(self):
        for delivery in self.delivery_set.all():
            for reply in delivery.reply_set.all():
                self.acknowledge("Reply %d from %s @ %s" % (reply.id, reply.delivery.contact, reply.dt_received))
        for phonecall in self.phonecall_set.all():
            if phonecall.dt_acked:
                self.acknowledge("PhoneCall %s - %s @ %s" % (phonecall.id, phonecall.contact, phonecall.dt_acked))

    def perform_escalation(self, dry_run = False):
        self.sync_acks()
        if self.get_status('acked') or not self.recipient.require_ack_min:
            return False

        debug("{%d} Performing escalation...", self.id)
        if not self.older_than(self.dt_received, self.recipient.require_ack_min):
            debug("Received less than ACK-mins ago -> nothing to do")
            return False

        if not self.get_status('called'):
            debug("Not yet called -> call now")
            if not dry_run:
                self.call_group()
            return True

        debug("Already called -> are we in CALL_GRACE period?")
        if not self.older_than(self.get_timestamp('called'), settings.CALL_GRACE_MIN):
            debug("Yes we are, called less than CALL_GRACE_MIN ago -> nothing to do")
            return False

        debug("Call to Primary Contact not ACKed in time")
        if not self.get_status('escalated'):
            debug("Not yet escalated -> escalate now")
            if not dry_run:
                return self.call_escalation_group()
            return True

        if self.older_than(self.get_timestamp('escalated'), settings.CALL_GRACE_MIN):
            debug("Escalated more than CALL_GRACE_MIN mins ago and not ACKed? -> Try again!")
            if not dry_run:
                # Call both the Group and Escalation Group if they are different
                self.call_group()
                if not self.recipient.escalation_group or self.recipient.escalation_group.contact_primary.sms_number == self.recipient.group.contact_primary.sms_number:
                    debug("Escalation Group not set or same as Primary Contact")
                else:
                    self.call_escalation_group()

        return True

    def call_group(self):
        message = "Alert for recipient %s. Group %s" % (self.recipient, self.recipient.group)
        return self.make_call(self.recipient.group, message)

    def call_escalation_group(self):
        if not self.recipient.escalation_group:
            self.add_status('escalated', note = "No escalation group set - call Primary Contact again")
            return self.make_call(self.recipient.group, "Alert for recipient %s. Group %s" % (self.recipient, self.recipient.group))
        else:
            self.add_status('escalated', note = "Calling escalation group %s" % self.recipient.escalation_group)
            return self.make_call(self.recipient.escalation_group, "Escalating alert for group %s. Was unable to contact %s." % (self.recipient.group.name, self.recipient.group.contact_primary.name))

    def make_call(self, group, text_to_say):
        if not self.recipient.can_call():
            self.add_status("not-called", note = "Call already in progress for recipient %s" % self.recipient)
            return False
        info("Calling '%s' [%s]: %s" % (group, group.contact_primary, text_to_say))
        pc = PhoneCall(message = self, contact = group.contact_primary, text_to_say = text_to_say)
        pc.save()
        self.recipient.update_last_called()
        self.add_status('called', note = text_to_say)
        pc.call()
        return True

templates/thialfi/detail.html
{% extends "_base.html" %}

{% block contentsub %}
{# just to kill it from rendering in _base.html #}
{% endblock %}

{% block contentfull %}
<h3 class="table-header">Message for group <strong>{{ message.recipient.group }}</strong> via <strong>{{ message.recipient }}</strong></h3>
<table class="message-detail u-full-width">
<tr><td class="label">From:</td><td class="content">{{ message.hdr_sender }}</td></tr>
<tr><td class="label">To:</td><td class="content">{{ message.hdr_recipient }}</td></tr>
<tr><td class="label">Subject:</td><td class="content">{{ message.hdr_subject }}</td></tr>
<tr><td class="label">Received:</td><td class="content">{{ message.dt_received }}</td></tr>
<tr><td class="label">Newest status:</td><td class="content">{{ message.newest_status.status }}</td></tr>
</table>
<h3 class="table-header">Status log</h3>
<table class="message-detail u-full-width">
{% for status in message.messagestatus_set.all %}
<tr><td>{{ status.dt_status }}</td><td>{{ status.status }}</td><td>{{ status.note }}</td></tr>
{% endfor %}
</table>
<pre class="u-full-width message-body">
{{ message.body }}
</pre>

{% if message.delivery_set.all %}
<h3 class="table-header">Delivery attempts</h3>
{% for delivery in message.delivery_set.all %}
<table class="message-detail u-full-width">
<tr><td class="label">Recipient:</td><td>{{ delivery.contact }}</td></tr>
<tr><td class="label">Status:</td><td>{{ delivery.status }}</td></tr>
<tr><td class="label">Despatched:</td><td>{{ delivery.dt_despatched }}</td></tr>
<tr><td class="label">Status updated:</td><td>{{ delivery.dt_status }}</td></tr>
<tr><td class="label">SMS ID:</td><td>{{ delivery.sms_id }}</td></tr>
</table>

{% if delivery.reply_set.all %}
<h3 class="table-header">Replies</h3>
{% for reply in delivery.reply_set.all %}
<table class="message-detail u-full-width">
<tr><td class="label">Message:</td><td>{{ reply.message }}</td></tr>
<tr><td class="label">Received:</td><td>{{ reply.dt_received }}</td></tr>
<tr><td class="label">Sender:</td><td>{{ reply.sender }}</td></tr>
</table>
{% endfor %}
{% endif %}

{% endfor %}
{% endif %}
{% endblock %}

templates/thialfi/group.html
{% extends "_base.html" %}

{% block contentsub %}
{% endblock %}

{% block contentfull %}
<h3>{{ group }}</h3>
<form action="{% url 'views_group' group.id %}" method="post">
{% csrf_token %}
<strong>Select on-call contact:</strong> <select name="contact">
{% for contact in group.contacts.all %}
<option value="{{ contact.id }}" {% if group.contact_primary == contact %}selected="1"{% endif %}>{{ contact }}</option>
{% endfor %}
</select>
<input class="button-primary" type="submit" value="Save" />
</form>
{% if error_message %}
<strong>{{ error_message }}</strong>
{% endif %}
<table class="u-full-width">
<thead>
    <tr>
        <th>Recipient address</th>
        <th>Description</th>
    </tr>
</thead>
<tbody>
{% for recipient in group.recipient_set.all %}
<tr>
    <td><a href="mailto:{{ recipient }}@{{ domain }}"><strong>{{ recipient }}</strong>@{{ domain }}</a></td>
    <td>{{ recipient.description }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

templates/thialfi/index.html
{% extends "_base.html" %}

{% block contentsub %}
{# just to kill it from rendering in _base.html #}
{% endblock %}

{% block contentfull %}
<h3>On-call groups</h3>
<table class="u-full-width">
<thead>
    <tr>
        <th>Group</th>
        <th>On-call Contact</th>
        <th>SMS Number</th>
    </tr>
</thead>
<tbody>
{% for group in groups %}
<tr>
<td><a href="{% url 'views_group' group_id=group.id %}">{{ group }}</a></td>
<td><a href="{% url 'views_group' group_id=group.id %}">{{ group.contact_primary.name }}</a></td>
<td>{{ group.contact_primary.sms_number }}</td>
</tr>
{% endfor %}
</tbody>
</table>
<p>Click the group name to change the On-Call contact and view group details.</p>
{% endblock %}

templates/thialfi/messages.html
{% extends "_base.html" %}

{% block contentsub %}
{# just to kill it from rendering in _base.html #}
{% endblock %}

{% block contentfull %}
<h3>Messages in the queue</h3>
<table class="u-full-width messages-list">
<thead>
    <tr>
        <th>Recipient</th>
        <th>Message</th>
        <th>Received</th>
        <th>Status</th>
    </tr>
</thead>
<tbody>
{% for message in messages %}
<tr class="{{ message.newest_status.status }}">
    <td class="recipient">{{ message.recipient }}</td>
    <td class="message"><a href="{% url 'views_detail' message_id=message.id %}">{{ message.hdr_subject }}</a></td>
    <td class="received">{{ message.dt_received }}</td>
    <td class="status">{{ message.newest_status.status }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}